import Head from 'next/head'
import Image from 'next/dist/client/image'
import styles from "../styles/scss/Main.module.scss"
import Header from "../components/Header"
import Banner from "../components/Banner"
import Discover from '../components/Discover'
import Footer from '../components/Footer'
import tryHosting from "../public/images/tryHosting.jpg"
export default function Home({nearByResults, liveAnyWhere}) {
  return (
    <div className = {styles.container}>

      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      
      <Banner />

      <main className = {styles.mainSection}>
        <h2>Explore NearBy</h2>
        <div className = {styles.mainSectionInner}>
          {nearByResults?.map(({img, location, distance}) =>(
            <div className = {styles.mainSectionInnerOne} key = {img}>
                <div className = {styles.mainSectionImages}>
                    <Image src = {img} width = "100%" height = "100%" />
                </div>
              
              
                <div className = {styles.mainSectionContent}>
                    <h4 className = {styles.mainSectionHeadingFour}>{location}</h4>
                    <h6 className = {styles.mainSectionHeadingSix}>{distance}</h6>
                </div>
            </div>
          ))}
        </div>
      </main>

      <section className = {styles.homeFirstSection}>
          <h2 className = {styles.homeFirstSectionHeadingTwo}>Live anywhere</h2>
          <div className = {styles.homeFirstSectionInner}>
            {liveAnyWhere.map(({img, title})=>(
              <div className = {styles.homeFirstSectionInnerCards} key = {img}>
                  <div className = {styles.homeFirstSectionInnerImage}>
                    <Image className = {styles.ImageCards} src = {img} layout="fill" />
                  </div>
                  <h3 className = {styles.homeFirstSectionHeadingThree}>{title}</h3>
              </div>
            ))}
          </div>
      </section>

      <section className = {styles.homeSecondSection}>
          <div className = {styles.homeSecondSectionInner}>
            <div className = {styles.homeSecondSectionInnerImage}>
                <Image className = {styles.homeSecondSectionInnerImageSection} src= {tryHosting} layout="fill" />
            </div>
            <div className = {styles.homeSecondSectionContent}>
                <h2 className = {styles.homeSecondSectionHeadingTwo}>Try hosting</h2>
                <p className = {styles.homeSecondSectionParagraph}>Earn extran income and unlock new 
                  opportunities by sharing your space.
                </p>
                <button type = "button">Learn more</button>
            </div>
        </div>
      </section>

      <Discover />
      <Footer />
    </div>
  )
}

export async function getStaticProps(){
  const nearByResults = await fetch("https://jsonkeeper.com/b/4G1G").
    then(
      (res) => res.json()
    );

  const liveAnyWhere = await fetch("https://jsonkeeper.com/b/VHHT").
    then(
      (res) => res.json()
    );
    return {
      props:{
        nearByResults,
        liveAnyWhere,
      }
    }
}